apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlZtVnVlV0Z0YVc1Q1lXdG9ZWEk2WjJsMGFIVmlYM0JoZEY4eE1VRkhTVGRJV2trd01reGliMUprVFZsRmNHOXhYMlpIVEhSRFZHdEpSRUpLVlZCdlJWZENjMGs0VEd4SFZETnZZMmhHTWxKUlIzbFJjR2h2V0hKVGVteE9ORTFOVnpSQlJsSjFaVVJXT0hscSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K
type: kubernetes.io/dockerconfigjson
